name: Trigger auto deployment for ksefpdfapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ksefpdfapi-AutoDeployTrigger-4d471039-7bd9-4613-a77b-2378456e297b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.KSEFPDFAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.KSEFPDFAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KSEFPDFAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Container App (Dockerfile)
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: api/Dockerfile

          # ACR
          acrName: comsoftksefpdf
          

          # nazwa obrazu + tag
          imageToBuild: comsoftksefpdf.azurecr.io/ksefpdfapi:${{ github.sha }}
          imageToDeploy: comsoftksefpdf.azurecr.io/ksefpdfapi:${{ github.sha }}

          containerAppName: ksefpdfapi3
          
          resourceGroup: rg-ksef-pdf

          acrUsername: ${{ secrets.KSEFPDFAPI_REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.KSEFPDFAPI_REGISTRY_PASSWORD }}








